all: ejecutablePersona ejecutableListas

#Generar personas - Primera Parte
ejecutablePersona: ./funcgenerarpersonas.o ./primeraParte/generarpersonas.c
    gcc -o ejecutablePersona ./primeraParte/generarpersonas.c ./primeraParte/funcgenerarpersonas.o


generarpersonas.o: ./primeraParte/funcgenerarpersonas.c ./primeraParte/funcgenerarpersonas.h
    gcc -c ./primeraParte/funcgenerarpersonas.c
    

#Ordenar listas - Segunda parte
ejecutableListas: dlist.o persona.o
    gcc -o ejecutableListas listaenlazada.c .dlist.o .persona.o

dlist.o: ./segundaParte/DList/dlist.c
    gcc -c ./segundaParte/DList/dlist.c

persona.o: ./segundaParte/Persona/persona.c
    gcc -c ./segundaParte/Persona/persona.c


